### PR TITLE
Use Functor in updateStats

### PR DESCRIPTION
**Pull request by drpowell**
This `updateStats` is definitely shorter, and perhaps clearer in intent.  Interested to know what you think.  I guess for a "beginner" the use of Functor and Alternative is not obvious...

Also, used Either in `prettyOutput` to allow error reporting.

### CODE REVIEW

**Comment by bjpop** [comment]
Thanks Dave.

I decided to make the code a bit more idiomatic and filter the minlen sequences out first. Also initialised the stats from the first sequence in the filtered list. This avoids of lot of Maybe junk.
I'm holding off on the "Not a FASTA file" because I want to check the desired behaviour.

In light of the above I won't pull this into the code. Appreciate the input however.

**Comment by drpowell** [comment]
Yep, fair enough, and I think your version is easier for others to understand.  Although I think use of fmap is more idiomatic

**Comment by bjpop** [comment]
Agreed. By idiomatic, I meant using filter and then using foldl', rather than bundling the two things together as I previously had done.

I agree that your fmap code was more idiomatic for handling the Maybes. If we really wanted to go full-blown modern Haskell then we could also have used a lens, but that is probably taking it too far.

I also borrowed your approach of using min and max to update the stats, rather than a conditional statement. I should have done that in the first place.

**Comment by drpowell** [comment]
I briefly considered lens, but figured pulling in most of hackage for this tool was a little overkill.

I actually prefer the Maybe approach for this than the approach of "there must be 1", but it's your call.

I'm surprised you aren't using the record update approach in updateStats which I think makes more readable, and less error-prone code?

**Comment by bjpop** [comment]
Do you want to send in a patch with record update approach? I'm not sure what you mean. Do you mean that I used positional arguments instead of named arguments, or is there something else I am missing. I would like to have less error-prone code.

**Pull request closed without merging**
